# %% IMPORT LIBRARIES AND SETUP

# Import the pandas library for data manipulation and analysis
import pandas as pd
# Import the numpy library for numerical operations and array handling
import numpy as np
# Import the pyplot module from matplotlib for creating visualizations
import matplotlib.pyplot as plt
# Import the main statsmodels API for statistical modeling
import statsmodels.api as sm
# Import AutoReg for autoregressive modeling and ar_select_order for lag selection
from statsmodels.tsa.ar_model import AutoReg, ar_select_order
# Import functions to plot the Autocorrelation and Partial Autocorrelation functions
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
# Import the warnings module to handle warning messages
import warnings

# Suppress all warnings to keep the console output clean
warnings.filterwarnings("ignore")

# Print a message indicating the start of the data download
print("Downloading macro data...")
# Define the URL pointing to the raw text file containing the GDP data
url = "https://faculty.chicagobooth.edu/-/media/faculty/ruey-s-tsay/teaching/fts3/q-gdp4708.txt"
# Read the dataset using pandas, specifying a regular expression for variable spaces
df = pd.read_csv(url, sep=r'\s+')
# Rename the 'mon' column to 'month' for compatibility with datetime functions
df = df.rename(columns={'mon': 'month'})

# Combine year, month, and day columns into a single pandas DatetimeIndex
df.index = pd.to_datetime(df[['year', 'month', 'day']])
# Infer and set the frequency of the time series index automatically
df.index.freq = df.index.inferred_freq

# Calculate the GDP growth rate by applying the natural logarithm and differencing it
df['growth'] = np.log(df['gdp']).diff()

# Create a new DataFrame dropping any missing values generated by the differencing
df_growth = df.dropna()

# Print a newline and a header for the data preview
print("\nData Head:")
# Print the first three rows of the dataset showing both level and growth
print(df_growth[['gdp', 'growth']].head(3))


# %% VISUAL ANALYSIS: LEVELS, GROWTH, ACF & PACF

# Print a separator line for visual clarity in the console
print("\n" + "="*50)
# Print the title for the first section of the analysis
print("VISUAL ANALYSIS: GDP GROWTH DYNAMICS")
# Print another separator line
print("="*50)

# Initialize a new figure object with specific width and height dimensions
plt.figure(figsize=(12, 6))

# Create the first subplot in a grid of 2 rows and 1 column
plt.subplot(2, 1, 1)
# Plot the raw GDP time series data in navy blue
plt.plot(df['gdp'], color='navy')
# Set the title for the upper subplot
plt.title('US Quarterly GDP (Level)')
# Enable a light grid to make the plot easier to read
plt.grid(True, alpha=0.3)

# Create the second subplot directly below the first one
plt.subplot(2, 1, 2)
# Plot the transformed GDP growth rate data in dark green
plt.plot(df_growth['growth'], color='darkgreen')
# Set the title for the lower subplot
plt.title('US Quarterly GDP Growth Rate (Log Difference)')
# Enable a light grid for the second subplot
plt.grid(True, alpha=0.3)

# Automatically adjust the padding between subplots to prevent overlapping text
plt.tight_layout()
# Display the combined levels and growth figure
plt.show()

# Initialize a new figure with two subplots side-by-side for the correlograms
fig, ax = plt.subplots(1, 2, figsize=(16, 4))
# Plot the Sample Autocorrelation Function (ACF) on the left subplot, ignoring lag 0
plot_acf(df_growth['growth'], lags=12, ax=ax[0], zero=False)
# Plot the Partial Autocorrelation Function (PACF) on the right subplot, ignoring lag 0
plot_pacf(df_growth['growth'], lags=12, ax=ax[1], zero=False)
# Display the correlograms figure
plt.show()

"""
DISCUSSION (Visual Analysis):
- Stationarity: GDP in levels grows exponentially and contains a stochastic trend 
  (it is non-stationary). Fitting an AR model directly to levels leads to spurious 
  regressions. Taking the log-difference transforms it into a stationary growth rate process.
- PACF Interpretation: The PACF shows a massive, highly significant spike at lag 1, 
  followed by much smaller values that quickly fall near or inside the blue confidence band. 
  This strong AR(1) signature justifies using a simple first-order autoregressive model 
  as a solid, parsimonious baseline.
"""


# %% AR(1) MODEL ESTIMATION

# Print a separator line for the estimation section
print("\n" + "="*50)
# Print the title for the model estimation part
print("AR(1) MODEL ESTIMATION")
# Print the closing separator line
print("="*50)

# Set the maximum number of lags to consider during the automatic selection process
max_lag_test = 12

# Automatically evaluate and select the best model using the BIC penalty (favors parsimony)
selector_bic = ar_select_order(df_growth['growth'], maxlag=max_lag_test, ic='bic')
# Extract the optimal list of lags chosen by the criterion
selected_lags_bic = selector_bic.ar_lags

# Print the array of lags chosen by the BIC criterion
print(f"Selected Lags (BIC): {selected_lags_bic}")

# Initialize and immediately fit an AR model with a single lag
model_ar1 = AutoReg(df_growth['growth'], lags=1).fit()

# Print a header indicating the start of the AR(1) model estimation
print("\n--- ESTIMATION: AR(1) MODEL ---")
# Print the full statistical summary of the fitted AR(1) model
print(model_ar1.summary())

"""
DISCUSSION (Estimation):
- Significance: The coefficient for the first lag (growth.L1) is approximately 0.47 
  with a p-value of 0.000. It is highly statistically significant at the 1% level, 
  confirming that past quarter growth is a strong linear predictor of current growth.
"""


# %% MACROECONOMIC DYNAMICS: PERSISTENCE OF SHOCKS

# Print a separator line for the macroeconomic dynamics section
print("\n" + "="*50)
# Print the title for the economic cycle analysis
print("ECONOMIC DYNAMICS (Based on AR(1))")
# Print the closing separator line
print("="*50)

# Extract the persistence of shocks directly from the AR(1) slope coefficient (index 1)
persistence = model_ar1.params.iloc[1]

# Print the calculated persistence metric formatted to four decimal places
print(f"Shock Persistence (AR(1) coefficient): {persistence:.4f}")

"""
DISCUSSION (Dynamics):
- Shock Persistence: The AR(1) coefficient is approximately 0.4715. This means the 
  economy has positive momentum. 
- Decay effect: If there is an unexpected +1.0% shock to GDP growth in Q1, the 
  growth rate in Q2 will be boosted by roughly +0.47% (1.0 * 0.4715). In Q3, the 
  residual effect will be +0.22% (0.4715^2). The shock decays exponentially, meaning 
  the economy gradually, smoothly reverts to its mean growth rate without cyclical swings.
"""


# %% FORECASTING (OUT-OF-SAMPLE)

# Print a separator line for the forecasting section
print("\n" + "="*50)
# Print the title for the forecasting analysis
print("FORECASTING (5 Steps Ahead)")
# Print the closing separator line
print("="*50)

# Define the number of steps to forecast (5 quarters ahead)
forecast_steps = 5

# Generate out-of-sample forecasts for the next 5 quarters using the fitted model
forecast_growth = model_ar1.forecast(steps=forecast_steps)

# Print the forecasted values
print(f"\nForecasted GDP Growth Rates for the next {forecast_steps} quarters:")
print(forecast_growth)

# Initialize a new figure object for the forecast plot
plt.figure(figsize=(10, 5))

# Plot the historical data. For better visual clarity, plot only the last 20 observations.
plt.plot(df_growth.index[-20:], df_growth['growth'].iloc[-20:], label='Historical Growth', color='darkgreen', marker='o')

# Plot the forecasted data. Statsmodels automatically generates the future DatetimeIndex.
plt.plot(forecast_growth.index, forecast_growth, label='Forecast', color='red', marker='x', linestyle='--')

# Set the title and labels
plt.title('US Quarterly GDP Growth: Historical and 5-Quarter Forecast')
plt.xlabel('Date')
plt.ylabel('Growth Rate (Log Difference)')
# Enable grid
plt.grid(True, alpha=0.3)
# Show legend
plt.legend()
# Display the plot
plt.show()

"""
DISCUSSION (Forecasting):
- Convergence: The AR(1) model is weakly stationary. Because of this, the multi-step-ahead 
  forecast gradually decays and flattens out. It is converging exponentially toward the 
  unconditional mean of the process (which is roughly 1.6% per quarter). Since we don't 
  have future shocks (we assume future error terms are strictly 0), the model simply 
  predicts a smooth, monotonous return to the long-run macroeconomic equilibrium.
"""