# %% IMPORT LIBRARIES AND SETUP

# Import the pandas library for data manipulation and analysis
import pandas as pd
# Import the numpy library for numerical operations and array handling
import numpy as np
# Import the pyplot module from matplotlib for creating visualizations
import matplotlib.pyplot as plt
# Import yfinance to download daily financial data directly from Yahoo Finance
import yfinance as yf
# Import the main statsmodels API for statistical modeling
import statsmodels.api as sm
# Import AutoReg for autoregressive modeling and ar_select_order for lag selection
from statsmodels.tsa.ar_model import AutoReg, ar_select_order
# Import the warnings module to handle warning messages
import warnings

# Suppress all warnings to keep the console output clean
warnings.filterwarnings("ignore")

# Print a separator line and a header for the data downloading section
print("="*50)
print("DATA COLLECTION: DAX 2022")
print("="*50)

# Define the ticker symbol for the DAX index on Yahoo Finance
ticker = "^GDAXI"
# Define the start and end dates for the year 2022
start_date = "2022-01-01"
# We use Jan 1st 2023 as end date to ensure we capture all days of December 2022
end_date = "2023-01-01"

print(f"Downloading daily data for {ticker}...")
# Download the historical market data using yfinance
df = yf.download(ticker, start=start_date, end=end_date, progress=False)

# Calculate the daily log returns using the Close price
df['return'] = np.log(df['Close']).diff()

# Calculate the squared daily returns (which serve as a proxy for daily variance/volatility)
df['sq_return'] = df['return'] ** 2

# Drop any missing values generated by the differencing
df = df.dropna()

# Print the first few rows to verify the data processing
print("\nData Head:")
print(df[['Close', 'return', 'sq_return']].head(3))


# %% 1. VISUAL ANALYSIS

# Print a separator line for the visual analysis section
print("\n" + "="*50)
# Print the title for the visual analysis
print("1. VISUAL ANALYSIS: RETURNS VS SQUARED RETURNS")
# Print the closing separator line
print("="*50)

# Initialize a new figure with two subplots stacked vertically
plt.figure(figsize=(12, 8))

# Create the top subplot for the standard returns
plt.subplot(2, 1, 1)
# Plot the standard daily returns in blue
plt.plot(df.index, df['return'], color='steelblue')
# Set the title for the first subplot
plt.title('DAX Daily Returns (2022)')
# Enable a light grid
plt.grid(True, alpha=0.3)

# Create the bottom subplot for the squared returns
plt.subplot(2, 1, 2)
# Plot the squared daily returns in red
plt.plot(df.index, df['sq_return'], color='firebrick')
# Set the title for the second subplot
plt.title('DAX Squared Daily Returns (Volatility Proxy)')
# Enable a light grid
plt.grid(True, alpha=0.3)

# Automatically adjust the padding between subplots
plt.tight_layout()
# Display the plots
plt.show()

"""
DISCUSSION (Visual Analysis):
- Volatility Clustering: 2022 was heavily impacted by macroeconomic shocks (e.g., Ukraine war). 
  The top plot shows that large price drops are clustered together. 
- The bottom plot (squared returns) makes this phenomenon perfectly clear: periods 
  of high variance are persistent. A tall red spike (high volatility today) is highly 
  likely to be followed by another tall red spike (high volatility tomorrow).
"""


# %% 2. MODELING SQUARED RETURNS (VOLATILITY DYNAMICS)

# Print a separator line for the squared returns modeling section
print("\n" + "="*50)
# Print the title for the squared returns analysis
print("2. AR(p) MODEL FOR SQUARED RETURNS")
# Print the closing separator line
print("="*50)

# Set the maximum number of lags to consider
max_lag_test = 10

# Manually compute and print the AIC for each lag to open the "black box" of model selection.
# CRITICAL: We use 'hold_back=max_lag_test' to force all models to be estimated on the 
# exact same sample size (N - 10). Without this, AR(0) would use 10 more observations 
# than AR(10), making their AIC scores mathematically incomparable.
print(f"Comparing AIC values for different AR(p) models (Fixed Sample: N-{max_lag_test}):")
for p in range(0, max_lag_test + 1):
    # Fit the temporary model for the current lag 'p' (p=0 is White Noise)
    model_temp = AutoReg(df['sq_return'], lags=p, hold_back=max_lag_test).fit()
    # Print the calculated Akaike Information Criterion
    print(f"AR({p:02d}) -> AIC: {model_temp.aic:.4f}")

# Automatically select the optimal lag order for SQUARED returns using the AIC
selector_sq = ar_select_order(df['sq_return'], maxlag=max_lag_test, ic='aic')
# Extract the list of selected lags
selected_lags_sq = selector_sq.ar_lags
# Determine the highest lag order (p), handling the NoneType if 0 lags are selected
p_sq = max(selected_lags_sq) if selected_lags_sq is not None else 0

print(f"\nOptimal AR order for Squared Returns (Minimum AIC): AR({p_sq})")

# Fit an AR(p) model to the SQUARED returns using the optimal lags selected by AIC
if p_sq > 0:
    model_sq = AutoReg(df['sq_return'], lags=selected_lags_sq).fit()
    # Print a header indicating the start of the model summary
    print(f"\n--- ESTIMATION: AR({p_sq}) ON SQUARED RETURNS ---")
    # Print the statistical summary of the fitted model
    print(model_sq.summary())
else:
    print("\n--- ESTIMATION: WHITE NOISE ---")
    print("AIC selected 0 lags for the squared returns.")

"""
DISCUSSION (Squared Returns & Model Selection):
- Fixed Sample: To ensure a valid "apples-to-apples" comparison, Information Criteria 
  (like AIC or BIC) must be computed over the exact same estimation sample. 
- AIC Minimization: Inspecting the manual table, the AIC value drops as we add lags, 
  hitting its absolute mathematical minimum exactly at AR(3), and then starts to rise 
  again as the penalty for complexity outweighs the improved fit.
- Implication: Variance is predictable. Knowing past volatility gives us significant 
  statistical power to predict current volatility.
"""

# %% 3. MODELING STANDARD RETURNS (PRICE DYNAMICS)

# Print a separator line for the standard returns modeling section
print("\n" + "="*50)
# Print the title for the standard returns analysis
print("3. AR(p) MODEL FOR STANDARD RETURNS")
# Print the closing separator line
print("="*50)

# Automatically select the optimal lag order for STANDARD returns using the AIC
selector_ret = ar_select_order(df['return'], maxlag=max_lag_test, ic='aic')
# Extract the list of selected lags
selected_lags_ret = selector_ret.ar_lags
# Determine the highest lag order (p), handling the NoneType if 0 lags are selected
p_ret = max(selected_lags_ret) if selected_lags_ret is not None else 0

print(f"Optimal AR order for Standard Returns (AIC): AR({p_ret})")

# Fit the AR(p) model to the STANDARD returns
if p_ret > 0:
    model_ret = AutoReg(df['return'], lags=selected_lags_ret).fit()
    print(f"\n--- ESTIMATION: AR({p_ret}) ON STANDARD RETURNS ---")
    print(model_ret.summary())
else:
    print("\n--- ESTIMATION: WHITE NOISE ---")
    print("AIC selected 0 lags. The standard returns behave as a pure White Noise process.")

"""
DISCUSSION (Comparative Analysis):
- Standard Returns: For the standard returns, the AIC typically selects 0 lags (or 
  perhaps 1 lag that is statistically insignificant). The past sequence of returns 
  contains no useful information to predict tomorrow's return direction.
- Conclusion: We observe an efficient market in the 'first moment' (mean): prices 
  follow a random walk and you cannot consistently predict if tomorrow will be up or down. 
  However, the market is highly inefficient in the 'second moment' (variance): 
  volatility is extremely persistent and predictable. You cannot predict the direction, 
  but you can predict the intensity of the movement!
"""