# %% IMPORT LIBRARIES AND SETUP

# Import the pandas library for data manipulation
import pandas as pd
# Import the numpy library for numerical operations
import numpy as np
# Import the pyplot module from matplotlib for visualizations
import matplotlib.pyplot as plt
# Import yfinance to download financial data directly from Yahoo Finance
import yfinance as yf
# Import the Augmented Dickey-Fuller test from statsmodels
from statsmodels.tsa.stattools import adfuller
# Import the warnings module to handle warning messages
import warnings

# Suppress all warnings to keep the console output clean
warnings.filterwarnings("ignore")

# Print a separator line and a header for the data downloading section
print("="*50)
print("DATA COLLECTION: AMZN, S&P 500, T-BILL (Monthly)")
print("="*50)

# Define the start date as requested
start_date = "2010-01-01"

print("Downloading data...")
# Define the list of tickers to download simultaneously
tickers = ["AMZN", "^GSPC", "^IRX"]

# Download all data in one go (this perfectly aligns dates and handles the yfinance MultiIndex)
raw_data = yf.download(tickers, start=start_date, interval="1mo", progress=False)

# Extract only the 'Close' prices DataFrame
df = raw_data['Close'].copy()

# Rename the columns to make them easier to work with
df = df.rename(columns={'^GSPC': 'SP500', '^IRX': 'TBILL_Ann_Pct'})

# Drop any rows with missing data that might occur due to trading holiday misalignments
df = df.dropna()

# Print the first few rows to verify the download
print("\nRaw Data Head:")
print(df.head(3))


# %% DATA TRANSFORMATION

print("\n" + "="*50)
print("DATA TRANSFORMATION: EXCESS RETURNS")
print("="*50)

# Calculate the simple monthly log returns for Amazon
df['AMZN_Ret'] = np.log(df['AMZN']).diff()

# Calculate the monthly Risk-Free Rate
# Note: ^IRX is quoted as an annualized percentage (e.g., 2.5 means 2.5% per year).
# We must divide by 100 to get a decimal, and by 12 to get the monthly rate.
df['Rf_Monthly'] = (df['TBILL_Ann_Pct'] / 100) / 12

# Calculate the Amazon excess return series (rt)
df['Excess_Ret'] = df['AMZN_Ret'] - df['Rf_Monthly']

# Drop the first NaN row generated by the difference
df = df.dropna()

print("Transformation complete. Head of excess returns:")
print(df[['AMZN_Ret', 'Rf_Monthly', 'Excess_Ret']].head(3))


# %% 1. VISUAL ANALYSIS

print("\n" + "="*50)
print("VISUAL ANALYSIS: AMAZON PRICE SERIES")
print("="*50)

# Initialize a new figure
plt.figure(figsize=(10, 5))
# Plot the AMZN price series
plt.plot(df.index, df['AMZN'], color='darkorange', linewidth=2)
# Add title and labels
plt.title('Amazon (AMZN) Monthly Closing Price (2010 - Present)')
plt.ylabel('Price (USD)')
plt.xlabel('Date')
# Enable grid
plt.grid(True, alpha=0.3)
# Show plot
plt.tight_layout()
plt.show()

"""
DISCUSSION (Visual Analysis):
- Non-Stationarity: A simple visual inspection clearly shows that the AMZN price 
  is NOT weakly stationary. 
- Violations: The mean is not constant (there is an obvious upward stochastic trend, 
  particularly accelerating during the 2020-2021 COVID tech boom). Furthermore, 
  the variance seems to increase as the price level increases over time.
"""


# %% 2. HYPOTHESIS TESTING (PRICES)

print("\n" + "="*50)
print("ADF TEST: AMZN PRICE SERIES")
print("="*50)

print("Null Hypothesis (H0): The series has a unit root (it is non-stationary).")
print("Alternative (H1): The series has no unit root (it is stationary).\n")

# Perform the Augmented Dickey-Fuller test on the AMZN prices
adf_prices = adfuller(df['AMZN'])

# Extract and print the key results from the ADF test output tuple
print(f"ADF Statistic: {adf_prices[0]:.4f}")
print(f"p-value:       {adf_prices[1]:.4f}")
print("Critical Values:")
for key, value in adf_prices[4].items():
    print(f"   {key}: {value:.4f}")

"""
DISCUSSION (Hypothesis Testing - Prices):
- Result: The p-value is extremely high (usually around 0.8 or 0.9 depending on 
  the exact end date). Furthermore, the ADF test statistic is greater than the 
  critical values at all significance levels (1%, 5%, 10%).
- Conclusion: We firmly FAIL to reject the null hypothesis. The test confirms our 
  visual intuition: the AMZN price series contains a unit root and is non-stationary.
"""


# %% 3. HYPOTHESIS TESTING (EXCESS RETURNS)

print("\n" + "="*50)
print("ADF TEST: AMZN EXCESS RETURNS")
print("="*50)

# Perform the ADF test on the Excess Returns series
adf_returns = adfuller(df['Excess_Ret'])

# Extract and print the key results
print(f"ADF Statistic: {adf_returns[0]:.4f}")
print(f"p-value:       {adf_returns[1]:.4f}")
print("Critical Values:")
for key, value in adf_returns[4].items():
    print(f"   {key}: {value:.4f}")

"""
DISCUSSION (Hypothesis Testing - Returns):
- Result: The p-value for the excess returns series is roughly 0.0000. The test 
  statistic is highly negative, massively exceeding the 1% critical value.
- Conclusion: We firmly REJECT the null hypothesis of a unit root. The excess 
  return series is weakly stationary.
- Econometric Implication: This confirms why we must transform price data into 
  returns before building predictive models (like ARMA). Running an AR regression 
  on raw prices would lead to a "spurious regression," violating the core 
  assumptions of OLS estimation.
"""