# %% IMPORT LIBRARIES AND SETUP
# Import the necessary libraries for downloading data, math operations, and regressions
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import warnings

# Suppress warnings to keep the console output clean
warnings.filterwarnings("ignore")

# Define the tickers: ExxonMobil (Y), S&P 500 (Market), Crude Oil (Commodity), 13-week T-Bill (Risk-Free)
tickers = ['XOM', '^GSPC', 'CL=F', '^IRX']

# Download daily historical data
print("Downloading data...")
data = yf.download(tickers, start='2010-01-01', end='2025-12-31', auto_adjust=True)['Close'].dropna()

# Calculate the daily log-returns for the assets
returns = np.log(data[['XOM', '^GSPC', 'CL=F']] / data[['XOM', '^GSPC', 'CL=F']].shift(1))

# Convert the annualized risk-free rate (^IRX) to a daily decimal rate
# Assuming 252 trading days in a year
rf_daily = (1 + data['^IRX'] / 100)**(1/252) - 1

# Calculate Excess Returns for the CAPM formulation
returns['XOM_excess'] = returns['XOM'] - rf_daily
returns['GSPC_excess'] = returns['^GSPC'] - rf_daily

# Drop missing values generated by the shift
returns = returns.dropna()

print("\nData Head (Excess Returns included):")
print(returns[['XOM_excess', 'GSPC_excess', 'CL=F']].head(3))


# %% 1. SIMPLE REGRESSION: THE MARKET MODEL (CAPM STYLE)
print("\n" + "="*50)
print("SIMPLE REGRESSION (CAPM): XOM Excess vs S&P 500 Excess")
print("="*50)

# Define Dependent (Y) and Independent (X) variables
Y = returns['XOM_excess']
X_simple = returns['GSPC_excess']

# Add a constant (intercept, representing Jensen's Alpha)
X_simple_const = sm.add_constant(X_simple)

# Fit the Ordinary Least Squares (OLS) model
model_simple = sm.OLS(Y, X_simple_const).fit()

# Print the regression results
print(model_simple.summary())

# --- PLOTTING THE SIMPLE REGRESSION (2D) ---
fig, ax = plt.subplots(figsize=(10, 6))

# Scatter plot of the actual observations
ax.scatter(X_simple, Y, color='dodgerblue', alpha=0.5, label='Daily Excess Returns')

# Create the regression line: y = alpha + beta * x
x_line = np.linspace(X_simple.min(), X_simple.max(), 100)
# iloc[0] is the intercept (alpha), iloc[1] is the slope (beta)
y_line = model_simple.params.iloc[0] + model_simple.params.iloc[1] * x_line

# Plot the regression line
ax.plot(x_line, y_line, color='red', linewidth=2, label=f'CAPM Line (Beta = {model_simple.params.iloc[1]:.2f})')

ax.set_title('Simple Regression (CAPM): ExxonMobil vs Market')
ax.set_xlabel('S&P 500 Excess Log-Returns')
ax.set_ylabel('ExxonMobil Excess Log-Returns')
ax.axhline(0, color='black', linestyle='--', alpha=0.3)
ax.axvline(0, color='black', linestyle='--', alpha=0.3)
ax.legend()
plt.grid(alpha=0.3)
plt.show()

"""
DISCUSSION (Simple Regression - CAPM):
1. Market Beta: ExxonMobil's Beta is around 0.80. Being less than 1, 
   it indicates that XOM is a "defensive" stock compared to the overall market, 
   fluctuating less in response to systemic shocks.
2. Intercept (Jensen's Alpha): The intercept represents Jensen's Alpha. In an efficient 
   market, especially on daily data, we expect this to be statistically indistinguishable 
   from zero, meaning the asset does not generate abnormal returns beyond its market risk.
"""


# %% 2. MULTIPLE REGRESSION: ADDING OIL PRICES
print("\n" + "="*50)
print("MULTIPLE REGRESSION: XOM vs S&P 500 & CRUDE OIL")
print("="*50)

# Define the new matrix of Independent variables (X_multi)
X_multi = returns[['GSPC_excess', 'CL=F']]

# Add a constant and fit the new OLS model
X_multi_const = sm.add_constant(X_multi)
model_multi = sm.OLS(Y, X_multi_const).fit()

# Print the multiple regression results
print(model_multi.summary())

# PLOTTING THE MULTIPLE REGRESSION (3D PLANE)
fig = plt.figure(figsize=(18, 12))
ax = fig.add_subplot(111, projection='3d')

# Scatter of actual data
ax.scatter(returns['GSPC_excess'], returns['CL=F'], returns['XOM_excess'], 
           color='dodgerblue', alpha=0.5, marker='o')

# Create the regression plane
x_range = np.linspace(returns['GSPC_excess'].min(), returns['GSPC_excess'].max(), 20)
y_range = np.linspace(returns['CL=F'].min(), returns['CL=F'].max(), 20)
X_surf, Y_surf = np.meshgrid(x_range, y_range)

# Equation of the plane: Z = alpha + beta_1*X1 + beta_2*X2
Z_surf = model_multi.params.iloc[0] + model_multi.params.iloc[1] * X_surf + model_multi.params.iloc[2] * Y_surf

# Plot the plane
ax.plot_surface(X_surf, Y_surf, Z_surf, color='red', alpha=0.4)

ax.set_title('Multiple Regression: XOM vs Market & Oil Prices')
ax.set_xlabel('S&P 500 Excess Returns (X1)')
ax.set_ylabel('Crude Oil Returns (X2)')
ax.set_zlabel('XOM Excess Returns (Y)')
# View angle for best visibility of the plane's tilt
ax.view_init(elev=20, azim=-45)

plt.show()

"""
DISCUSSION (Multiple Regression):
1. Commodity Exposure: The Crude Oil (CL=F) coefficient is approximately 0.2267 with a 
   p-value of 0.000. This makes perfect economic sense: for every 1% increase in crude oil 
   prices, Exxon's excess returns increase by roughly 0.22% on average, holding the market constant.
2. R-squared: The R-squared is around 0.474. This is an excellent result for daily financial 
   data, meaning that nearly 48% of the daily variance in ExxonMobil's returns is explained 
   solely by these two macroeconomic variables.
"""